### PR TITLE
Drop dependency on deprecated `gulp-util`

### LINKED ISSUE #84: Replace deprecated dependency gulp-util
[`gulp-util`](https://www.npmjs.com/package/gulp-util) has been deprecated recently. Continuing to use this dependency may prevent the use of your library with the latest release of Gulp 4 so **it is important to replace `gulp-util`**.

The [README.md](https://github.com/gulpjs/gulp-util) lists alternatives for all the components so a simple replacement should be enough.

Your package is popular but still relying on `gulp-util`, it would be good to publish a fixed version to npm as soon as possible.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- https://github.com/gulpjs/gulp-util/issues/143

### PR DESCRIPTION
**Pull request by TheDancingCode**
Closes #84

### CODE REVIEW

**Comment by TheDancingCode** [comment]
@wiledal 
Did you get a chance to look at this?

**Comment by TheDancingCode** [comment]
Another friendly reminder.

**Comment by TheDancingCode** [comment]
@wiledal or anyone else: any takers?

**Comment by petermonte** [comment]
Is this getting merged?

**Comment by rifler** [comment]
friendly bump

**Comment by KenEucker** [comment]
In light of the recent flatmap-stream drama, I feel that it is important to address and resolve issues like this in a timely manner instead of letting widely used packages like this fall to mismanagement. This PR is almost a year old. 

Is there anyone here who can merge this in?

@wiledal 
@scottmas

**Comment by WordsofDefiance** [comment]
I will be removing gulp-include from my projects until this gets fixed.

**Comment by KenEucker** [comment]
friendly bump

**Comment by tsktech** [comment]
friendly bump

**Comment by KenEucker** [comment]
UPDATE:

I was able to have a conversation with the maintainer, @wiledal, and have agreed to provisionally join the github project to address the open pull requests. I am going to take some time to respond to the ones that seem the most important but I also urge anyone to make comments on any items that they feel are pertinent. 

After I've approved and merged a few of the more important PRs (dependency updates), I will ask the community to pull down the master branch and test it before we publish a new version to NPM.

Thank you for your patience and understanding!

**Pull request closed without merging**
