### PR TITLE
throw error if file not found

### PR DESCRIPTION
**Pull request by raniesantos**
I fixed the problems mentioned in these issues.
- [Fail on file not found #37](https://github.com/wiledal/gulp-include/issues/37)
- [Errors don't appear on console when file is not found #59](https://github.com/wiledal/gulp-include/issues/59)
Please merge.

### CODE REVIEW

**Comment by claviska** [comment]
Why on earth would file not found *not* trigger an error? Would love to see this implemented.

**Comment by giyyapan** [comment]
Any update? Would love to see this implemented too.

**Comment by wiledal** [comment]
Added errors if no match if met in version 2.2.1.

**Comment by wiledal** [comment]
Slight change to this.
Errors are soft by default now, `gulp-include` will WARN in the console. If you need errors to be thrown, add the `hardFail: true` param after version 2.3.x.

**Pull request closed without merging**
